---
- name: Disable SWAP in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Ensure kernel modules config
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
    content: |
      {% for module in k8s_kernel_modules %}
      {{ module }}
      {% endfor %}

- name: Load kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ k8s_kernel_modules }}"

- name: Set sysctl params
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ k8s_sysctl_params }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ k8s_required_packages }}"
    state: present

- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download apt keys
  ansible.builtin.get_url:
    url: "{{ item.key_url }}"
    dest: "{{ item.key_tmp }}"
    mode: "0644"
  loop: "{{ k8s_repositories }}"

- name: Convert apt keys to gpg format
  ansible.builtin.command:
    cmd: "gpg --dearmor -o {{ item.keyring }} {{ item.key_tmp }}"
  args:
    creates: "{{ item.keyring }}"
  loop: "{{ k8s_repositories }}"

- name: Add apt repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.name }}"
    state: present
  loop: "{{ k8s_repositories }}"

- name: Install kubernetes components
  ansible.builtin.apt:
    name: "{{ k8s_packages }}"
    state: present
    update_cache: true

- name: Hold kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ k8s_hold_packages }}"

- name: Start crio
  ansible.builtin.systemd_service:
    name: crio.service
    state: started
    enabled: true